title: "Elektroslav"
description: "Нотатки з математики, програмування та скетчінгу"
url: "https://elektroslav.github.io"
baseurl: "https://elektroslav.github.io"
repository: "elektroslav/elektroslav.github.io"

theme: minimal-mistakes-jekyll

markdown: kramdown
kramdown:
  math_engine: mathjax
mathjax:
  enable: true

locale: "en" # базова мова

# Navigation меню
collections:
  pages:
    output: true
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
      toc: true
