title: "Elektroslav"
author: "Elektroslav"
theme: minima

navigation:
  - title: "Головна"
    url: "/uk/"
  - title: "Home"
    url: "/en/"
  - title: "Про мене"
    url: "/en/about/"
  - title: "Проекти"
    url: "/en/projects/"
  - title: "Контакти"
    url: "/en/contact/"

minima:
  skin: auto
  social_links: []
  include_css: assets/css/custom.css

markdown: kramdown
kramdown:
  math_engine: mathjax